variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
    
stages:
  - deploy

deploy:
  image: dtzar/helm-kubectl:3.10.3
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=admin --namespace=default
    - kubectl config use-context default
    - helm repo add nexus $HELM_REPO --username $HELM_REPO_USER --password $HELM_REPO_PASS
    - helm repo update
    - helm upgrade momo-store-frontend nexus/momo-store-frontend -i --atomic --set fqdn=$FQDN