---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: default
  annotations:
    ingress.alb.yc.io/subnets: {{ .Values.SubnetId }}
    ingress.alb.yc.io/external-ipv4-address: {{ .Values.IngressExternalIp }}
    ingress.alb.yc.io/group-name: "momo-store-alb-group"
spec:
  tls:
    - hosts:
        - monitoring.{{ .Values.fqdn }}
      secretName: yc-certmgr-cert-id-{{ .Values.certid }}
  rules:
    - host: monitoring.{{ .Values.fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
